version: "3.9"
services:
    lemurro-traefik:
        container_name: lemurro-traefik
        image: "traefik:2.9"
        command:
            - --providers.docker
            - --api
            - --api.dashboard=true
            - --api.insecure=true
            - --providers.docker=true
            - --providers.docker.exposedByDefault=false
            - --entrypoints.http.address=:80
            - --log
        ports:
            - "80:80"
            - "8080:8080"
        networks:
            - traefik-public
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        labels:
            - traefik.enable=true
            - traefik.docker.network=traefik-public
            - traefik.http.routers.traefik.entrypoints=http
            - traefik.http.routers.traefik.rule=Host(`traefik.localhost`)
            - traefik.http.services.traefik.loadBalancer.server.port=80

    lemurro-api:
        container_name: api
        build:
            context: api/docker
            dockerfile: dev/nginx/Dockerfile
        volumes:
            - ./api:/app:rw
        networks:
            - traefik-public
            - default
        labels:
            - traefik.enable=true
            - traefik.docker.network=traefik-public
            - traefik.http.routers.api.entrypoints=http
            - traefik.http.routers.api.rule=Host(`api.localhost`)
            - traefik.http.services.api.loadBalancer.server.port=80

    php-fpm:
        container_name: php-fpm
        build:
            context: api/docker
            dockerfile: dev/php-fpm/Dockerfile
        volumes:
            - ./api:/app:rw

    php-cli:
        container_name: php-cli
        build:
            context: api/docker
            dockerfile: dev/php-cli/Dockerfile
        volumes:
            - ./api:/app:rw

    mariadb:
        image: mariadb:latest
        container_name: mariadb
        restart: always
        environment:
            MYSQL_USER: adminer
            MYSQL_PASSWORD: adminer
            MYSQL_DATABASE: lemurro
            MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: true
        ports:
            - 5555:3306
        networks:
            - default
        volumes:
            - db_data:/var/lib/mysql

    adminer:
        image: adminer:latest
        container_name: adminer
        environment:
            ADMINER_DEFAULT_SERVER: mariadb
        restart: always
        ports:
            - 7777:8080
        networks:
            - traefik-public
            - default
        labels:
            - traefik.enable=true
            - traefik.docker.network=traefik-public
            - traefik.http.routers.adminer.entrypoints=http
            - traefik.http.routers.adminer.rule=Host(`adminer.localhost`)
            - traefik.http.services.adminer.loadBalancer.server.port=80

volumes:
    db_data:

networks:
    traefik-public:
        external: true